version: '3.4'
services:
  aqua-postgres:
    image: timescale/timescaledb-postgis:2.0.1-pg12
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: '!ChangeMe!'
    volumes:
      - ./db_data:/var/lib/postgresql
